# Generated by Django 4.0.4 on 2022-07-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descicao',
            new_name='descricao',
        ),
    ]
